# This file is part of twes-in.
#
# (c) Takieddine MESSAOUDI <takieddine.messaoudi.official@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# ==============================================================================================================
# twes-in — the one place the compose invocation lives.
#
# WHY A MAKEFILE RATHER THAN A README FULL OF COMMANDS. Every target below needs the same project directory and
# the same env-file chain. Getting either wrong is not a typo that fails loudly — it silently reads a different
# `.env`, or applies production hardening to a dev stack. A README cannot enforce that; this can.
#
# HOW THE COMPOSE FILES COMPOSE, which changed on 2026-08-02 and is the reason there is no `-f` on the dev
# targets. Docker Compose AUTO-LOADS `compose.override.yaml` next to `compose.yaml` — but ONLY when no `-f` is
# passed, because `-f` switches it into explicit mode and the override is then silently ignored. So the dev
# targets `cd infra` and let discovery do its job, which is both the conventional spelling and the one that
# cannot forget the overlay. Production is explicit, because `compose.prod.yaml` must NEVER be picked up by
# accident.
# ==============================================================================================================

SHELL := /bin/bash
.DEFAULT_GOAL := help

INFRA := infra

# `.env` is committed with safe defaults and EMPTY secrets; `.env.local` is gitignored and holds the real ones.
# Compose reads `.env` from the project directory automatically, but passing `--env-file` at all switches that
# off — so both are named explicitly, and `.env.local` only when it exists, or compose errors on a missing file.
ENV_FLAGS := --env-file .env $(if $(wildcard $(INFRA)/.env.local),--env-file .env.local,)

# Dev: no `-f`, so `compose.override.yaml` is auto-merged. Prod: explicit, so it never is.
DC      := cd $(INFRA) && docker compose $(ENV_FLAGS)
DC_PROD := cd $(INFRA) && docker compose $(ENV_FLAGS) -f compose.yaml -f compose.prod.yaml

.PHONY: help
help: ## Show this help.
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'

# --------------------------------------------------------------------------------------------------------------
# Environment
# --------------------------------------------------------------------------------------------------------------
.PHONY: env
env: ## Generate infra/.env.local with fresh random secrets. Refuses to overwrite an existing one.
	@if [ -f $(INFRA)/.env.local ]; then \
		echo "$(INFRA)/.env.local already exists — refusing to overwrite it."; \
		echo "Delete it first if you really want new secrets (this invalidates the existing database)."; \
		exit 1; \
	fi
	@command -v openssl >/dev/null || { echo "openssl is required to generate secrets."; exit 1; }
	@{ \
		echo "# Machine-local secrets. GITIGNORED — never commit this file."; \
		echo "# Generated by \`make env\`. Layered over the committed infra/.env by every compose invocation."; \
		echo "APP_SECRET=$$(openssl rand -hex 32)"; \
		echo "POSTGRES_PASSWORD=$$(openssl rand -hex 24)"; \
		echo "TWES_DB_RUNTIME_PASSWORD=$$(openssl rand -hex 24)"; \
		echo "TWES_DB_OWNER_PASSWORD=$$(openssl rand -hex 24)"; \
	} > $(INFRA)/.env.local
	@echo "Wrote $(INFRA)/.env.local with four fresh secrets. Nothing else needs editing to run locally."

.PHONY: check-env
check-env:
	@[ -f $(INFRA)/.env.local ] || { \
		echo "$(INFRA)/.env.local is missing — the stack has no secrets and would refuse to start."; \
		echo "    make env"; \
		exit 1; \
	}

# --------------------------------------------------------------------------------------------------------------
# Development
# --------------------------------------------------------------------------------------------------------------
.PHONY: up
up: check-env ## Start the development stack (source-mounted, database published on localhost).
	$(DC) up -d --build
	@echo
	@$(MAKE) --no-print-directory urls

.PHONY: urls
urls: ## Print the local URLs.
	@port=$$(grep -hE '^HTTP_PORT=' $(INFRA)/.env.local $(INFRA)/.env 2>/dev/null | head -1 | cut -d= -f2); \
	port=$${port:-8080}; \
	echo "  API      http://localhost:$$port/api"; \
	echo "  Docs     http://localhost:$$port/api/docs"; \
	echo "  Health   http://localhost:$$port/health/ready"; \
	echo "  Admin    http://localhost:$$port/admin/   (run 'make build-front' first)"; \
	echo "  Flutter  http://localhost:$$port/app/     (run 'make build-front' first)"

.PHONY: down
down: ## Stop the development stack, keeping volumes.
	$(DC) down

.PHONY: destroy
destroy: ## Stop the stack and DELETE ITS DATA. Irreversible.
	@printf 'This deletes the database volume. Type "yes" to continue: ' && read ans && [ "$$ans" = yes ]
	$(DC) down --volumes

.PHONY: logs
logs: ## Follow logs from every service.
	$(DC) logs -f --tail=100

.PHONY: ps
ps: ## Show the state of every service.
	$(DC) ps

.PHONY: shell
shell: ## Open a shell in the API container.
	$(DC) exec api sh

.PHONY: console
console: ## Run a Symfony console command: make console CMD="debug:router"
	@[ -n "$(CMD)" ] || { echo 'CMD="<console command>" is required, e.g. make console CMD=debug:router'; exit 1; }
	$(DC) exec api php bin/console $(CMD)

# --------------------------------------------------------------------------------------------------------------
# Build
# --------------------------------------------------------------------------------------------------------------
.PHONY: build
build: check-env ## Build the API image.
	$(DC) build api

.PHONY: build-front
build-front: check-env ## Build the Angular and Flutter bundles into the volumes the API serves.
	$(DC) run --rm --build admin-build
	$(DC) run --rm --build flutter-build

# --------------------------------------------------------------------------------------------------------------
# Database
# --------------------------------------------------------------------------------------------------------------
.PHONY: migrate
migrate: check-env ## Run migrations. Uses the OWNING role -- the only place that credential is used.
	$(DC) run --rm migrate

.PHONY: psql
psql: ## Open psql against the stack's database as the superuser.
	$(DC) exec database psql --username "$${POSTGRES_USER:-postgres}" --dbname "$${POSTGRES_DB:-twes}"

.PHONY: backup
backup: ## Dump the database to infra/backups/ with a UTC timestamp.
	@mkdir -p $(INFRA)/backups
	@stamp=$$(date -u +%Y%m%dT%H%M%SZ); \
	$(DC) exec -T database \
		pg_dump --username "$${POSTGRES_USER:-postgres}" --dbname "$${POSTGRES_DB:-twes}" --format=custom \
		> "backups/twes-$$stamp.dump" && echo "wrote $(INFRA)/backups/twes-$$stamp.dump"

.PHONY: restore
restore: ## Restore from a dump: make restore DUMP=backups/twes-....dump  (path relative to infra/)
	@[ -n "$(DUMP)" ] || { echo "DUMP=<path relative to infra/> is required"; exit 1; }
	@printf 'This OVERWRITES the current database. Type "yes" to continue: ' && read ans && [ "$$ans" = yes ]
	$(DC) exec -T database \
		pg_restore --username "$${POSTGRES_USER:-postgres}" --dbname "$${POSTGRES_DB:-twes}" --clean --if-exists \
		< "$(DUMP)"

# --------------------------------------------------------------------------------------------------------------
# Production
# --------------------------------------------------------------------------------------------------------------
.PHONY: up-prod
up-prod: check-env ## Start the production stack (hardened, HTTPS, replicas).
	$(DC_PROD) up -d --build

.PHONY: down-prod
down-prod: ## Stop the production stack.
	$(DC_PROD) down

.PHONY: config-prod
config-prod: ## Render the production configuration without starting anything.
	$(DC_PROD) config

# --------------------------------------------------------------------------------------------------------------
# Quality
# --------------------------------------------------------------------------------------------------------------
.PHONY: gate
gate: ## Run the API tier's full quality gate on the host.
	cd api && COMPOSER_ALLOW_SUPERUSER=1 composer gate

.PHONY: gate-infra
gate-infra: ## Validate every compose configuration renders and holds its security properties.
	bash scripts/gates/compose-config.sh
