# This file is part of twes-in.
#
# (c) Takieddine MESSAOUDI <takieddine.messaoudi.official@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# ==============================================================================================================
# twes-in — the one place the compose invocation lives.
#
# WHY A MAKEFILE RATHER THAN A README FULL OF COMMANDS. Every target below needs the same project directory and
# the same env-file chain. Getting either wrong is not a typo that fails loudly — it silently reads a different
# `.env`, or applies production hardening to a dev stack. A README cannot enforce that; this can.
#
# HOW THE COMPOSE FILES COMPOSE, which changed on 2026-08-02 and is the reason there is no `-f` on the dev
# targets. Docker Compose AUTO-LOADS `compose.override.yaml` next to `compose.yaml` — but ONLY when no `-f` is
# passed, because `-f` switches it into explicit mode and the override is then silently ignored. So the dev
# targets `cd infra` and let discovery do its job, which is both the conventional spelling and the one that
# cannot forget the overlay. Production is explicit, because `compose.prod.yaml` must NEVER be picked up by
# accident.
# ==============================================================================================================

SHELL := /bin/bash
.DEFAULT_GOAL := help

INFRA := infra

# `.env` is committed with safe defaults and EMPTY secrets; `.env.local` is gitignored and holds the real ones.
# Compose reads `.env` from the project directory automatically, but passing `--env-file` at all switches that
# off — so both are named explicitly, and `.env.local` only when it exists, or compose errors on a missing file.
ENV_FLAGS := --env-file .env $(if $(wildcard $(INFRA)/.env.local),--env-file .env.local,)

# THE HOST'S REAL uid/gid, exported so the dev image builds a user matching whoever is running make. Without this
# the dev container writes into the bind-mounted `api/` tree as the wrong owner, which fails one of two ways: it
# cannot create `vendor/` at all, or it creates root-owned files in the developer's working copy. `TWES_` prefixed
# because plain `UID` is special in some shells and cannot be exported reliably.
export TWES_UID := $(shell id -u)
export TWES_GID := $(shell id -g)

# Dev: no `-f`, so `compose.override.yaml` is auto-merged. Prod: explicit, so it never is.
DC      := cd $(INFRA) && docker compose $(ENV_FLAGS)
DC_PROD := cd $(INFRA) && docker compose $(ENV_FLAGS) -f compose.yaml -f compose.prod.yaml

.PHONY: help
help: ## Show this help.
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'

# --------------------------------------------------------------------------------------------------------------
# Environment
# --------------------------------------------------------------------------------------------------------------
.PHONY: env
env: ## Generate infra/.env.local with fresh random secrets. Refuses to overwrite an existing one.
	@if [ -f $(INFRA)/.env.local ]; then \
		echo "$(INFRA)/.env.local already exists — refusing to overwrite it."; \
		echo "Delete it first if you really want new secrets (this invalidates the existing database)."; \
		exit 1; \
	fi
	@command -v openssl >/dev/null || { echo "openssl is required to generate secrets."; exit 1; }
	@{ \
		echo "# Machine-local secrets. GITIGNORED — never commit this file."; \
		echo "# Generated by \`make env\`. Layered over the committed infra/.env by every compose invocation."; \
		echo "APP_SECRET=$$(openssl rand -hex 32)"; \
		echo "POSTGRES_PASSWORD=$$(openssl rand -hex 24)"; \
		echo "TWES_DB_RUNTIME_PASSWORD=$$(openssl rand -hex 24)"; \
		echo "TWES_DB_OWNER_PASSWORD=$$(openssl rand -hex 24)"; \
	} > $(INFRA)/.env.local
	@echo "Wrote $(INFRA)/.env.local with four fresh secrets. Nothing else needs editing to run locally."

.PHONY: check-env
check-env:
	@[ -f $(INFRA)/.env.local ] || { \
		echo "$(INFRA)/.env.local is missing — the stack has no secrets and would refuse to start."; \
		echo "    make env"; \
		exit 1; \
	}

# --------------------------------------------------------------------------------------------------------------
# Development
# --------------------------------------------------------------------------------------------------------------
.PHONY: up
up: check-env deps ## Start the development stack (source-mounted, database published on localhost).
	$(DC) up -d --build
	@echo
	@$(MAKE) --no-print-directory urls

.PHONY: urls
# `OpenAPI`, and NOT `Docs http://.../api/docs`, which is what this printed until 2026-08-04. That path returns 404 to
# a BROWSER — `{"detail":"Swagger UI, ReDoc and Scalar are disabled.","status":404}` — because
# `config/packages/api_platform.yaml` deliberately ships no HTML documentation UI: they fetch remote assets, and that
# is a same-origin and privacy question this project has already ruled on for the Flutter build. So the URL was not
# broken, it was advertising a feature we chose not to have.
#
# Easy to miss, and worth recording HOW it was missed: `curl` with no `Accept` header gets 200 on that path, because
# content negotiation hands it the machine-readable document. Only a real browser, sending `Accept: text/html`, gets
# the 404. It surfaced from a screenshot, which is exactly the case CLAUDE.md's visual-evidence rule exists for.
#
# `.jsonopenapi` is the format name API Platform registers for OpenAPI here; `/api/docs.json` is NOT a route and 404s.
urls: ## Print the local URLs.
	@port=$$(grep -hE '^HTTP_PORT=' $(INFRA)/.env.local $(INFRA)/.env 2>/dev/null | head -1 | cut -d= -f2); \
	port=$${port:-8080}; \
	echo "  API      http://localhost:$$port/api"; \
	echo "  OpenAPI  http://localhost:$$port/api/docs.jsonopenapi"; \
	echo "  Health   http://localhost:$$port/health/ready"; \
	echo "  Admin    http://localhost:$$port/admin/   (run 'make build-front' first)"; \
	echo "  Flutter  http://localhost:$$port/app/     (run 'make build-front' first)"

.PHONY: down
down: ## Stop the development stack, keeping volumes.
	$(DC) down

.PHONY: destroy
destroy: ## Stop the stack and DELETE ITS DATA. Irreversible.
	@printf 'This deletes the database volume. Type "yes" to continue: ' && read ans && [ "$$ans" = yes ]
	$(DC) down --volumes

.PHONY: logs
logs: ## Follow logs from every service.
	$(DC) logs -f --tail=100

.PHONY: ps
ps: ## Show the state of every service.
	$(DC) ps

.PHONY: shell
shell: ## Open a shell in the API container.
	$(DC) exec api sh

.PHONY: console
console: ## Run a Symfony console command: make console CMD="debug:router"
	@[ -n "$(CMD)" ] || { echo 'CMD="<console command>" is required, e.g. make console CMD=debug:router'; exit 1; }
	$(DC) exec api php bin/console $(CMD)

# --------------------------------------------------------------------------------------------------------------
# Build
# --------------------------------------------------------------------------------------------------------------
.PHONY: build
build: check-env ## Build the API image.
	$(DC) build api

.PHONY: build-front
build-front: check-env ## Build PRODUCTION Angular and Flutter bundles into the volumes the API serves.
	$(DC) run --rm --build admin-build
	$(DC) run --rm --build flutter-build

.PHONY: build-front-dev
# DEVELOPMENT bundles: Angular unminified with source maps, Flutter in `profile`. The point is a browser stack trace
# that names our file and line instead of `main-4f2a91.js:1:88231`, and a debugger that steps through TypeScript and
# Dart rather than compiler output.
#
# NOT `flutter --debug`: Flutter's web debug build uses DDC rather than dart2js, so it can behave differently from
# what ships — the wrong thing to hand somebody chasing a rendering bug. `profile` keeps the real compiler.
#
# The image TAGS carry the configuration (see compose.yaml), so this and `build-front` cannot collide in the build
# cache. Without that, running this and then `build-front` would be a cache hit that silently served the unminified
# bundle WITH OUR TYPESCRIPT SOURCE MAPS in production.
#
# TARGET-SCOPED `export`, NOT a leading assignment — AND THIS TARGET SHIPPED BROKEN FOR ONE COMMIT because the
# lesson was written down forty lines below and not applied here. `$(DC)` expands to `cd infra && docker compose ...`,
# so `NG_CONFIGURATION=development $(DC) run ...` sets the variable for the `cd` and compose never sees it. Compose
# then falls back to its own `${NG_CONFIGURATION:-production}` default and this target built the PRODUCTION bundle
# under the production tag — byte-identical work to `make build-front`, reported as a development build.
#
# [Verified: `sh -c 'FOO=bar cd /tmp && env | grep -c ^FOO='` -> 0; and the compose render under the old spelling
# reported `args={'NG_CONFIGURATION': 'production'}`.] Note the second-order failure: because the TAG also came out
# `production-dev`, the tag-carries-the-configuration protection was inert too, so nothing downstream could notice.
build-front-dev: export NG_CONFIGURATION := development
build-front-dev: export FLUTTER_BUILD_MODE := profile
build-front-dev: check-env ## Build DEVELOPMENT front-end bundles (source maps, unminified).
	$(DC) run --rm --build admin-build
	$(DC) run --rm --build flutter-build

# --------------------------------------------------------------------------------------------------------------
# PHP dependencies — installed BY THE CONTAINER, ONTO THE HOST TREE.
#
# This is what makes an IDE work, and the reason it is not simply "run composer on your machine": the container's
# PHP is the one that must resolve `ext-bcmath`, `ext-intl` and `ext-pdo_pgsql` and pick versions against PHP 8.5,
# so a host Composer with a different PHP would produce a subtly different `vendor/` — the classic "works on my
# machine". Running it in the container and letting the bind mount put the bytes on the host gives both: resolved by
# the container, readable by the IDE.
#
# `--no-deps` so this does not start the database, and `--entrypoint composer` to bypass the API entrypoint, which
# would otherwise demand APP_SECRET and wait for a database that is not running.
# --------------------------------------------------------------------------------------------------------------
.PHONY: install
install: ## (Re)install PHP dependencies into api/vendor, using the container's PHP.
	$(DC) run --rm --no-deps --build --entrypoint composer api \
		install --no-interaction --no-progress $(COMPOSER_FLAGS)
	@echo "api/vendor is on the host now — point your IDE's PHP interpreter at the container and it will resolve."

.PHONY: deps
# The cheap guard `up` depends on. A bind-mounted `api/` REPLACES the image's vendor tree, so if the host has no
# `vendor/` the container has none either and every command dies with `Failed to open stream: autoload.php`. This
# makes the first `make up` on a fresh clone work without the developer having to know that.
deps:
	@[ -f api/vendor/autoload.php ] || { \
		echo "api/vendor is missing — installing it in the container first (one time)."; \
		$(MAKE) --no-print-directory install; \
	}

.PHONY: composer
composer: ## Run Composer in the container: make composer CMD="require symfony/uid"
	@[ -n "$(CMD)" ] || { echo 'CMD="<composer args>" is required, e.g. make composer CMD="require symfony/uid"'; exit 1; }
	$(DC) run --rm --no-deps --entrypoint composer api $(CMD)

# --------------------------------------------------------------------------------------------------------------
# Xdebug. OFF by default because `xdebug.mode=debug` costs roughly 2-5x on EVERY request even with no IDE attached,
# which is how a debugger becomes something a developer disables on day two and never switches back on.
#
# `start_with_request=trigger` means even when armed, only requests carrying `XDEBUG_TRIGGER` (or the
# `XDEBUG_SESSION` cookie every IDE browser extension sets) are debugged — so the stack stays fast while you debug.
#
# IDE path mapping, which is the other half and is configured in the IDE:  /app  <->  <this repo>/api
# --------------------------------------------------------------------------------------------------------------
# A TARGET-SCOPED `export`, and NOT `XDEBUG_MODE=... $(DC) up`, which is what these said first and which silently
# did nothing. `$(DC)` expands to `cd infra && docker compose ...`, so a leading assignment applies to the `cd` —
# the command right after it — and `docker compose` then runs without the variable at all. The target reported
# "Xdebug ARMED" while the container still had `xdebug.mode=off`. [Verified: `container XDEBUG_MODE=[off]` after
# `make debug-on`.] `export` puts it in the recipe's whole environment, where compose interpolation can see it.
.PHONY: debug-on
debug-on: export XDEBUG_MODE := debug,develop
debug-on: ## Arm Xdebug (step debugger) and recreate the API containers.
	$(DC) up -d --force-recreate api worker scheduler
	@$(MAKE) --no-print-directory debug-status
	@echo "  Listen on port 9003, ide key 'twes', and map  /app  ->  $(CURDIR)/api"
	@echo "  Only requests carrying XDEBUG_TRIGGER are debugged, so the stack stays fast."

.PHONY: debug-off
debug-off: export XDEBUG_MODE := off
debug-off: ## Disarm Xdebug and recreate the API containers.
	$(DC) up -d --force-recreate api worker scheduler
	@$(MAKE) --no-print-directory debug-status

.PHONY: debug-status
# READ THE VALUE BACK OUT OF THE RUNNING CONTAINER rather than echoing what we intended. The first version of
# `debug-on` printed "ARMED" unconditionally and was wrong for exactly one commit; a target that asserts its own
# success is how that goes unnoticed. This asks PHP.
debug-status: ## Report whether Xdebug is armed, as the running container sees it.
	@mode=$$($(DC) exec -T api php -d display_errors=0 -r 'echo ini_get("xdebug.mode") ?: "off";' 2>/dev/null | tail -1); \
	case "$$mode" in \
		off|'') echo "Xdebug is INSTALLED and DISARMED (xdebug.mode=off) — no cost per request." ;; \
		*)      echo "Xdebug is ARMED (xdebug.mode=$$mode)." ;; \
	esac

.PHONY: test
test: ## Run the API test suites inside the container.
	$(DC) exec api php tools/bin/phpunit-12.phar $(ARGS)

# --------------------------------------------------------------------------------------------------------------
# Database
# --------------------------------------------------------------------------------------------------------------
.PHONY: migrate
migrate: check-env ## Run migrations. Uses the OWNING role -- the only place that credential is used.
	$(DC) run --rm migrate

.PHONY: psql
psql: ## Open psql against the stack's database as the superuser.
	$(DC) exec database psql --username "$${POSTGRES_USER:-postgres}" --dbname "$${POSTGRES_DB:-twes}"

.PHONY: backup
backup: ## Dump the database to infra/backups/ with a UTC timestamp.
	@mkdir -p $(INFRA)/backups
	@stamp=$$(date -u +%Y%m%dT%H%M%SZ); \
	$(DC) exec -T database \
		pg_dump --username "$${POSTGRES_USER:-postgres}" --dbname "$${POSTGRES_DB:-twes}" --format=custom \
		> "backups/twes-$$stamp.dump" && echo "wrote $(INFRA)/backups/twes-$$stamp.dump"

.PHONY: restore
restore: ## Restore from a dump: make restore DUMP=backups/twes-....dump  (path relative to infra/)
	@[ -n "$(DUMP)" ] || { echo "DUMP=<path relative to infra/> is required"; exit 1; }
	@printf 'This OVERWRITES the current database. Type "yes" to continue: ' && read ans && [ "$$ans" = yes ]
	$(DC) exec -T database \
		pg_restore --username "$${POSTGRES_USER:-postgres}" --dbname "$${POSTGRES_DB:-twes}" --clean --if-exists \
		< "$(DUMP)"

# --------------------------------------------------------------------------------------------------------------
# Production
# --------------------------------------------------------------------------------------------------------------
.PHONY: up-prod
up-prod: check-env ## Start the production stack (hardened, HTTPS, replicas).
	$(DC_PROD) up -d --build

.PHONY: down-prod
down-prod: ## Stop the production stack.
	$(DC_PROD) down

.PHONY: config-prod
config-prod: ## Render the production configuration without starting anything.
	$(DC_PROD) config

# --------------------------------------------------------------------------------------------------------------
# Quality
# --------------------------------------------------------------------------------------------------------------
.PHONY: gate
gate: ## Run the API tier's full quality gate on the host.
	cd api && COMPOSER_ALLOW_SUPERUSER=1 composer gate

.PHONY: gate-infra
gate-infra: ## Validate every compose configuration renders and holds its security properties.
	bash scripts/gates/compose-config.sh
