<?php

/*
 * This file is part of twes-in.
 *
 * (c) Takieddine MESSAOUDI <takieddine.messaoudi.official@gmail.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

declare(strict_types=1);

namespace Twes\Migrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The Symfony Messenger transport table.
 *
 * **WHY A MIGRATION RATHER THAN `auto_setup`.** The Doctrine transport creates this table itself on first use,
 * and it does so on the RUNTIME connection — which would make the restricted `twes` role its OWNER.
 * `scripts/gates/schema-tenancy.php` refuses ANY table owned by the runtime role, tenant-owned or not, and the
 * reason is not pedantry: a runtime role that owns one table proves migrations are running as that role, so the
 * next tenant-owned table it creates is one `ALTER TABLE ... DISABLE ROW LEVEL SECURITY` from every tenant's
 * data. That is not hypothetical — `doctrine_migration_versions` in the local development database was exactly
 * this on 2026-08-01 (CLAUDE.md § Gotchas). So `auto_setup=false` in the DSN, and the table is created here,
 * where `doctrine_migrations.connection: owner` guarantees the right owner.
 *
 * **THIS TABLE IS NOT TENANT-OWNED, and that is a decision rather than an omission.** A queued message is
 * infrastructure: it carries a serialized payload whose tenant is inside the message body, and the worker binds
 * the tenant when it handles it. Giving the table a `company_id` and an RLS policy would break the transport,
 * because `messenger:consume` polls with no tenant bound and a fail-closed policy would hide every row from it.
 * The isolation obligation therefore moves INTO the handler — no tenant-less path may hydrate a domain
 * aggregate, which is the boundary rule CLAUDE.md § Gotchas settled on 2026-07-31. Recorded here because this is
 * the first non-tenant table the product adds on purpose, and the next reader will and should ask.
 *
 * **THE DDL IS DOCTRINE'S OWN, NOT REMEMBERED.** It was emitted by calling
 * `Connection::configureSchema()` against a PostgreSQL platform and reading `Schema::toSql()`, rather than
 * copied from documentation — a hand-written approximation of a table another component queries is how a
 * `queue_name VARCHAR(190)` becomes a `VARCHAR(255)` and the index stops being used. Note also that
 * `getExtraSetupSqlForTable()` is deprecated in Symfony 8.1 and returns `[]`, so unlike older versions there is
 * no LISTEN/NOTIFY trigger or function to create alongside it. [Verified: read
 * `vendor/symfony/doctrine-messenger/Transport/DoctrineTransport.php`.]
 */
final class Version20260802090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Symfony Messenger transport table, owned by the migrating role rather than auto-created by the application.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'twes-in targets PostgreSQL only — see CLAUDE.md § Architecture.',
        );

        $this->addSql(
            'CREATE TABLE messenger_messages ('
            . 'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'body TEXT NOT NULL, '
            . 'headers TEXT NOT NULL, '
            . 'queue_name VARCHAR(190) NOT NULL, '
            . 'created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            . 'available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            . 'delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            . 'PRIMARY KEY (id))',
        );

        // The transport's own composite index, in the transport's own column order. `messenger:consume` polls
        // with `WHERE queue_name = ? AND available_at <= ? AND delivered_at IS NULL ORDER BY available_at`, so a
        // different order here would leave that query on a sequential scan of a table that grows with throughput.
        $this->addSql(
            'CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 '
            . 'ON messenger_messages (queue_name, available_at, delivered_at, id)',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS messenger_messages');
    }
}
