<?php

/*
 * This file is part of twes-in.
 *
 * (c) Takieddine MESSAOUDI <takieddine.messaoudi.official@gmail.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

declare(strict_types=1);

namespace Twes\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Twes\Infrastructure\Tenancy\PostgresRowLevelSecurityIsolation;

/**
 * The document tables, and the row-level security that makes them tenant-owned.
 *
 * **HAND-WRITTEN, not generated by `doctrine:migrations:diff`.** A diff produces the four `CREATE TABLE`
 * statements and nothing else — it cannot know about row-level security, and a tenant-owned table without RLS is
 * completely unpoliced while looking finished. `assertPolicedTablesAreBeyondThisRolesReach()` derives its subject
 * set from tables that already HAVE row security, so a table missing it is invisible to that check by
 * construction (round 7 filed that precisely). This migration therefore issues the isolation statements itself,
 * and `scripts/gates/schema-tenancy.php` is what stops the next one forgetting the RLS statements. **It DOES check
 * KEY SHAPES, so the composite keys below are proven both by catalogue introspection and by attack.** This paragraph
 * said the key axis "moved to `BehaviouralIsolationTest` on 2026-08-01" and that was true for exactly one day: the
 * axis was RESTORED to the gate on 2026-08-02 after two certification lenses independently reproduced a cross-tenant
 * oracle without it, and `CLAUDE.md` § Architecture records why the round trip is the useful part — a probe's reach
 * is bounded by its fixture's value space, so a soft-delete partial unique index is invisible to an attack suite in
 * both directions. Key shapes are a CATALOGUE property. Corrected in place rather than annotated below, per
 * § Gotchas 2026-07-29.
 *
 * **The policy SQL comes from `policySqlFor()` rather than being written out here**, so the migration and the
 * checker cannot disagree. That is the same "one definition" rule the rest of this codebase follows for tax and
 * money: a second copy of the canonical tenant predicate is how a table ends up policed by something that only
 * resembles isolation. Round 12 found a policy that MENTIONED `twes.tenant_id` without isolating by it.
 *
 * **What is deliberately NOT here: role grants.** Which roles may read these tables, and the requirement that
 * the runtime role neither owns them nor holds `TRUNCATE`, is provisioning — `scripts/dev/provision-test-database.sh`
 * for the test cluster and `infra/README.md` for a deployment. A migration runs AS the owner, so a migration that
 * granted the runtime role its own privileges would be the owner deciding its own security policy, and the
 * separation of those two roles is the whole point (CLAUDE.md § Gotchas, the round-4 P0).
 */
final class Version20260801120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Document, line, charge and gapless-number tables, each tenant-owned with row-level security.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'This migration issues row-level-security statements, which are PostgreSQL-specific. twes-in targets '
            . 'PostgreSQL only — see CLAUDE.md § Architecture — so running it elsewhere would silently produce '
            . 'unpoliced tenant tables rather than a portable schema.',
        );

        $this->addSql(
            'CREATE TABLE document ('
            . 'company_id UUID NOT NULL, '
            . 'id UUID NOT NULL, '
            . 'type VARCHAR(32) NOT NULL, '
            . 'state VARCHAR(32) NOT NULL, '
            . 'currency CHAR(3) NOT NULL, '
            . 'number BIGINT DEFAULT NULL, '
            . 'vat_rounding_point VARCHAR(32) NOT NULL, '
            . 'PRIMARY KEY (company_id, id))',
        );

        // The gapless sequence's only real cross-process guarantee — see DocumentNumberSequence, which states
        // that it cannot promise uniqueness itself. NULL numbers do not collide in PostgreSQL, so drafts are
        // unaffected and only issued documents are constrained.
        $this->addSql(
            'CREATE UNIQUE INDEX document_number_unique_per_tenant_and_type '
            . 'ON document (company_id, type, number)',
        );

        $this->addSql(
            'CREATE TABLE document_line ('
            . 'company_id UUID NOT NULL, '
            . 'document_id UUID NOT NULL, '
            . 'position SMALLINT NOT NULL, '
            . 'quantity NUMERIC(21, 6) NOT NULL, '
            . 'unit_net NUMERIC(19, 4) NOT NULL, '
            . 'vat_rate NUMERIC(27, 12) NOT NULL, '
            . 'PRIMARY KEY (company_id, document_id, position))',
        );

        $this->addSql(
            'CREATE TABLE document_charge ('
            . 'company_id UUID NOT NULL, '
            . 'document_id UUID NOT NULL, '
            . 'position SMALLINT NOT NULL, '
            . 'label TEXT NOT NULL, '
            . 'amount NUMERIC(19, 4) NOT NULL, '
            . 'PRIMARY KEY (company_id, document_id, position))',
        );

        $this->addSql(
            'CREATE TABLE document_number_sequence ('
            . 'company_id UUID NOT NULL, '
            . 'type VARCHAR(32) NOT NULL, '
            . 'next_value BIGINT NOT NULL, '
            . 'PRIMARY KEY (company_id, type))',
        );

        // COMPOSITE foreign keys. A single-column FK on document_id alone would let one tenant reference — and
        // therefore cascade-delete — another tenant's document, so the tenant column is part of the reference
        // rather than merely present on the row. ON DELETE CASCADE is safe precisely BECAUSE it is composite.
        $this->addSql(
            'ALTER TABLE document_line ADD CONSTRAINT document_line_belongs_to_document '
            . 'FOREIGN KEY (company_id, document_id) REFERENCES document (company_id, id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE document_charge ADD CONSTRAINT document_charge_belongs_to_document '
            . 'FOREIGN KEY (company_id, document_id) REFERENCES document (company_id, id) ON DELETE CASCADE',
        );

        // CHECK constraints rather than native PostgreSQL enums, and that is forced by our own migration
        // settings: `doctrine_migrations.transactional` is true, and PostgreSQL refuses to add an enum value and
        // use it in the same transaction. [Verified: `BEGIN; ALTER TYPE t ADD VALUE 'c'; SELECT 'c'::t;` gives
        // `ERROR: unsafe use of new value "c" of enum type t`.] A CHECK is dropped and recreated inside a
        // transaction freely, so it evolves WITH the migration rather than against it.
        //
        // The values are the enums' BACKED values, never their case names: a PHP rename must not be a data
        // migration.
        $this->addSql(
            "ALTER TABLE document ADD CONSTRAINT document_type_is_known "
            . "CHECK (type IN ('invoice', 'quote', 'credit', 'delivery_note'))",
        );
        $this->addSql(
            "ALTER TABLE document ADD CONSTRAINT document_state_is_known "
            . "CHECK (state IN ('draft', 'issued', 'cancelled'))",
        );
        $this->addSql(
            "ALTER TABLE document ADD CONSTRAINT document_vat_rounding_point_is_known "
            . "CHECK (vat_rounding_point IN ('per_rate_group', 'per_line'))",
        );
        $this->addSql(
            "ALTER TABLE document_number_sequence ADD CONSTRAINT document_number_sequence_type_is_known "
            . "CHECK (type IN ('invoice', 'quote', 'credit', 'delivery_note'))",
        );

        // Matches DocumentNumberSequence's second guarantee — the first number handed out is 1. Enforced here as
        // well as in the domain deliberately: the domain refusal gives a caller a usable error, and the
        // constraint stops a direct UPDATE writing state the domain could not then read back.
        $this->addSql(
            'ALTER TABLE document_number_sequence ADD CONSTRAINT document_number_sequence_starts_at_one '
            . 'CHECK (next_value >= 1)',
        );

        // A number is either absent or at least 1, for the same reason: DocumentNumber refuses 0 and below.
        $this->addSql(
            'ALTER TABLE document ADD CONSTRAINT document_number_is_positive '
            . 'CHECK (number IS NULL OR number >= 1)',
        );

        // ROW-LEVEL SECURITY on every tenant-owned table. `document_number_sequence` is in this list and that was
        // once missed: a counter that leaks across tenants leaks one tenant's document volume to another, and an
        // unpoliced counter is writable by any tenant, which is a denial of service on somebody else's numbering.
        foreach (self::tenantOwnedTables() as $table) {
            foreach (PostgresRowLevelSecurityIsolation::policySqlFor($table) as $statement) {
                $this->addSql($statement);
            }
        }
    }

    public function down(Schema $schema): void
    {
        // Children first: the composite foreign keys are ON DELETE CASCADE, but DROP TABLE is not a delete.
        $this->addSql('DROP TABLE IF EXISTS document_line');
        $this->addSql('DROP TABLE IF EXISTS document_charge');
        $this->addSql('DROP TABLE IF EXISTS document_number_sequence');
        $this->addSql('DROP TABLE IF EXISTS document');
    }

    /**
     * The tables this migration creates that hold tenant data, and therefore need isolating.
     *
     * A named list rather than "every table this migration created", because the two are not the same thing and
     * conflating them is how an unpoliced table appears: a future join table, an audit log or a shared reference
     * table may legitimately have no tenant column, and a check that assumes otherwise would either refuse it or
     * — worse — police it on a column that does not mean what it looks like.
     *
     * @return list<string>
     */
    private static function tenantOwnedTables(): array
    {
        return [
            'document',
            'document_line',
            'document_charge',
            'document_number_sequence',
        ];
    }
}
