<?php

/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * SPDX-FileCopyrightText: Takieddine MESSAOUDI
 */

declare(strict_types=1);

/**
 * Shared by the licence gate and the notices generator: ONE reading of the two lock files, so the gate
 * checks exactly what the notices record.
 *
 * A dependency record is ['tier' => 'api'|'web', 'name', 'version', 'licence' (SPDX string or ''), 'dev' => bool].
 *
 * @return list<array{tier: string, name: string, version: string, licence: string, dev: bool}>
 */
function dependencyInventory(string $root): array
{
    $records = [];

    $composer = readJson($root.'/api/composer.lock');
    foreach (['packages' => false, 'packages-dev' => true] as $section => $dev) {
        foreach ($composer[$section] ?? [] as $package) {
            $licence = $package['license'] ?? [];
            $records[] = [
                'tier' => 'api',
                'name' => (string) $package['name'],
                'version' => ltrim((string) $package['version'], 'v'),
                'licence' => implode(' AND ', array_map('strval', (array) $licence)),
                'dev' => $dev,
            ];
        }
    }

    $npm = readJson($root.'/web/package-lock.json');
    $seen = [];
    foreach ($npm['packages'] ?? [] as $path => $package) {
        if ('' === $path) {
            continue; // the workspace itself
        }
        $name = substr((string) $path, (int) strrpos('/'.$path, 'node_modules/') + strlen('node_modules/') - 1);
        $licence = $package['license'] ?? '';
        if (is_array($licence)) {
            $licence = (string) ($licence['type'] ?? '');
        }
        $dev = (bool) ($package['dev'] ?? false);
        $key = $name.'@'.$package['version'];
        // The same package can be nested several times; one row per name and version, runtime winning over dev.
        if (isset($seen[$key]) && !$dev) {
            $records[$seen[$key]]['dev'] = false;
        }
        if (isset($seen[$key])) {
            continue;
        }
        $seen[$key] = count($records);
        $records[] = ['tier' => 'web', 'name' => $name, 'version' => (string) $package['version'], 'licence' => (string) $licence, 'dev' => $dev];
    }

    usort($records, static fn (array $a, array $b): int => [$a['tier'], $a['name'], $a['version']] <=> [$b['tier'], $b['name'], $b['version']]);

    return $records;
}

/** @return array<string, mixed> */
function readJson(string $path): array
{
    if (!is_file($path)) {
        throw new RuntimeException(sprintf('%s is missing', $path));
    }
    $decoded = json_decode((string) file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);
    if (!is_array($decoded)) {
        throw new RuntimeException(sprintf('%s is not a JSON object', $path));
    }

    return $decoded;
}

/**
 * Vendored font FILES under web/public and web/src (not packages): one record per directory holding a font file,
 * with the licence identified from the LICENSE text beside the files. The licence is '' when there is no LICENSE
 * and 'unknown' when its text names no licence recognised here; the gate refuses both, the notices list every one.
 *
 * @return list<array{dir: string, files: list<string>, licence: string}>
 */
function vendoredFonts(string $root): array
{
    $byDir = [];
    foreach (['web/public', 'web/src'] as $base) {
        if (!is_dir($root.'/'.$base)) {
            continue;
        }
        $files = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root.'/'.$base, FilesystemIterator::SKIP_DOTS));
        foreach ($files as $file) {
            if ($file instanceof SplFileInfo && $file->isFile() && 1 === preg_match('/\.(woff2?|ttf|otf)$/i', $file->getFilename())) {
                $byDir[substr($file->getPath(), strlen($root) + 1)][] = $file->getFilename();
            }
        }
    }
    ksort($byDir);

    $fonts = [];
    foreach ($byDir as $dir => $names) {
        sort($names);
        $fonts[] = ['dir' => (string) $dir, 'files' => $names, 'licence' => fontLicence($root.'/'.$dir.'/LICENSE')];
    }

    return $fonts;
}

/** The SPDX identifier a font LICENSE file carries, recognised from its text; the SIL wording is the only one known. */
function fontLicence(string $path): string
{
    if (!is_file($path)) {
        return '';
    }

    return 1 === preg_match('/SIL Open Font License,?\s+Version 1\.1/i', (string) file_get_contents($path)) ? 'OFL-1.1' : 'unknown';
}

/**
 * The notices document, rendered deterministically from the inventory and the vendored fonts. The gate compares the
 * file on disk to this.
 *
 * @param list<array{tier: string, name: string, version: string, licence: string, dev: bool}> $records
 * @param list<array{dir: string, files: list<string>, licence: string}>                     $fonts
 */
function renderNotices(array $records, array $fonts = []): string
{
    $out = "# Third-party notices\n\n";
    $out .= "<!-- GENERATED by scripts/notices/generate-third-party-notices.php from api/composer.lock, web/package-lock.json and the vendored font files. Do not edit by hand: regenerate, and the licence gate checks it is current. -->\n\n";
    $out .= "twes-in is AGPL-3.0-or-later with a commercial licence (see `LICENSING.md`). Every package below is\n";
    $out .= "permissive under the policy in that file, as enforced by `scripts/gates/dependency-licences.php`.\n";
    $out .= "Base images and service containers (PostgreSQL, nginx, Gotenberg, Mailpit, FrankenPHP) are aggregated,\n";
    $out .= "not compiled into what we distribute, and are not listed here.\n";

    foreach (['api' => 'api (Composer)', 'web' => 'web (npm)'] as $tier => $title) {
        $rows = array_values(array_filter($records, static fn (array $r): bool => $r['tier'] === $tier));
        $runtime = count(array_filter($rows, static fn (array $r): bool => !$r['dev']));
        $out .= sprintf("\n## %s — %d runtime, %d dev\n\n| Package | Version | Licence | Role |\n|---|---|---|---|\n", $title, $runtime, count($rows) - $runtime);
        foreach ($rows as $r) {
            $out .= sprintf("| %s | %s | %s | %s |\n", $r['name'], $r['version'], '' === $r['licence'] ? '(none declared)' : $r['licence'], $r['dev'] ? 'dev' : 'runtime');
        }
    }

    if ([] !== $fonts) {
        $out .= sprintf("\n## Vendored fonts — %d\n\nShipped unmodified, each with its licence text in the same directory.\n\n| Directory | Licence | Files |\n|---|---|---|\n", count($fonts));
        foreach ($fonts as $f) {
            $out .= sprintf("| %s | %s | %s |\n", $f['dir'], '' === $f['licence'] ? '(no LICENSE)' : $f['licence'], implode(', ', $f['files']));
        }
    }

    return $out;
}

/** @return array{root: string, flags: list<string>} */
function parseArguments(array $argv): array
{
    $root = dirname(__DIR__, 2);
    $flags = [];
    for ($i = 1; $i < count($argv); ++$i) {
        if ('--root' === $argv[$i] && isset($argv[$i + 1])) {
            $root = rtrim($argv[++$i], '/');
            continue;
        }
        $flags[] = (string) $argv[$i];
    }

    return ['root' => $root, 'flags' => $flags];
}
